name: sx

on:
     schedule:
     - cron: '45 2 * * *'
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install dependencies
        run: pip install opencv-python requests        
      
      - name: Run iptv
        run: python ${{ github.workspace }}/sxzb.py
         
      - name: Commit results
        run: |
            git config --local user.email "ahua0321@github.com"
            git config --local user.name "ahua"
            if [ -n "$(git status --porcelain)" ]; then
            git commit -am "Automatic update"
            git push
            else
              echo "No changes detected, skipping commit."
            fi
